### ISSUE TITLE
Invalid Game Data

### ISSUE THREAD

**Issue by SiriosDev** [ASchoe311/RiotGamesLibrary#4]
![image](https://github.com/user-attachments/assets/bf3a9de8-5b1c-4a52-b59d-654547b8d67b)
During editing it brings up this alert that blocks any editing, I believe it is due to incorrect handling of the `action` which is assigned to the individual game instead of being integrated to the addon

Example of other library addon:
![image](https://github.com/user-attachments/assets/ce66ba0d-d130-4c4d-8652-e866fedc6fb4)

Example of this addon:
![image](https://github.com/user-attachments/assets/0783289f-21d9-4e97-a417-2295c2e1cdcd)

**Comment by ASchoe311** [comment]
I believe the issue here is that tracking mode is by default set to folder but it didn't detect your league of legends installation and fill in the folder information. This causes the action to be invalid. I will try to figure out a fix for this because unfortunately folder tracking seems to be the only way to properly track playtime

**Comment by ASchoe311** [comment]
> ![image](https://private-user-images.githubusercontent.com/26876994/368929832-bf3a9de8-5b1c-4a52-b59d-654547b8d67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjY1NDEsIm5iZiI6MTcyNjgyNjI0MSwicGF0aCI6Ii8yNjg3Njk5NC8zNjg5Mjk4MzItYmYzYTlkZTgtNWIxYy00YTUyLWI1OWQtNjU0NTQ3YjhkNjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDBlODVlNTJlZTNiMDljMjMzMzliY2RlZjg0Yjc0MzU2YjZmN2NjM2FhMmQxM2ZlZDI5MDViYmNjY2VlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBP41oowrF_rMfPpXxFyQ9cq2xnkm1Er70cvcmzV6G0) During editing it brings up this alert that blocks any editing, I believe it is due to incorrect handling of the `action` which is assigned to the individual game instead of being integrated to the addon
> 
> Example of other library addon: ![image](https://private-user-images.githubusercontent.com/26876994/368930793-ce66ba0d-d130-4c4d-8652-e866fedc6fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjY1NDEsIm5iZiI6MTcyNjgyNjI0MSwicGF0aCI6Ii8yNjg3Njk5NC8zNjg5MzA3OTMtY2U2NmJhMGQtZDEzMC00YzRkLTg2NTItZTg2NmZlZGM2ZmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NGFmNzg0YWY3YjdkZGRlYzQwMWNjZDA4NmVhM2FiYTM5NGNkMzAwNmYwYThmYzNmOTdhZjRjZjIzZGEzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Uw4IaGqzCXBz9ub9_FofJUo3waxyxoFufWUnkDtr6J0)
> 
> Example of this addon: ![image](https://private-user-images.githubusercontent.com/26876994/368930971-0783289f-21d9-4e97-a417-2295c2e1cdcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjY1NDEsIm5iZiI6MTcyNjgyNjI0MSwicGF0aCI6Ii8yNjg3Njk5NC8zNjg5MzA5NzEtMDc4MzI4OWYtMjFkOS00ZTk3LWE0MTctMjI5NWMyZTFjZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTY1ZTk1YmM0N2Y5NDczMWRjY2M5ODZiYjhlNTFlZWZjNDFiZWRhNDViZDZjNjhhMmMxMDhjNTFhNmQ1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nOmDay05loha1ZGpsOvDZMmCePl5o6akDBxcByfVW3M)

The fix seems to be creating an integrated play action as per your images. I have completed this on the branch [IntegratedPlayActions](https://github.com/ASchoe311/RiotGamesLibrary/tree/IntegratedPlayActions) and will release it soon once I have finished checking for any bugs.
